- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-description
  requirements:
  - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs
  - !type:SpeciesRequirement
    inverted: true
    species:
    - IPC
  guides: [ Changelings ]
