- type: antag
  id: Heretic
  name: roles-antag-heretic-name
  antagonist: true
  setPreference: true
  objective: roles-antag-heretic-description
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 14400 # 4h
  guides: [ Heretics ]

- type: startingGear
  id: HereticGear
  storage:
    back:
    - CodexCicatrix
    - OrganHumanHeart
